server:
  port: 8081
spring:
  application:
    name: content-center
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1(10%)
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        cluster-name: BJ
    sentinel:
      transport:
        # 控制台配置
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 128.0.0.1:9876
      bindings:
        output:
          # 用来指定topic
          destination: stream-test-topic
        my-output:
          # 用来指定topic
          destination: stream-my-topic
  main:
    allow-bean-definition-overriding: true
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  level:
    com.itmuch.contentcenter.feignclient: debug
    com.alibaba.nacos: error

feign:
  sentinel:
    # 为feign启用sentinel
    enabled: true
  client:
    config:
      #全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.itmuch.contentcenter.feignclient.interceptor.TokenRelayRequestInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # 小坑：必须指定group
    group: test-group

jwt:
  secret: dhu1b312b3u2h1b3hk
  expire-time-in-second: 1209600